<h1 id="exception-handling">Exception Handling</h1>
<p>JavaScript has an <code>Error</code> class that you can use for exceptions. You throw an error with the <code>throw</code> keyword. You can catch it with a <code>try</code> / <code>catch</code> block pair e.g.</p>
<pre><code class="lang-js"><span class="hljs-keyword">try</span> {
  <span class="hljs-keyword">throw</span> <span class="hljs-keyword">new</span> <span class="hljs-built_in">Error</span>(<span class="hljs-string">'Something bad happened'</span>);
}
<span class="hljs-keyword">catch</span>(e) {
  <span class="hljs-built_in">console</span>.log(e);
}
</code></pre>
<h2 id="error-sub-types">Error Sub Types</h2>
<p>Beyond the built in <code>Error</code> class there are a few additional built-in error classes that inherit from <code>Error</code> that the JavaScript runtime can throw:</p>
<h3 id="rangeerror">RangeError</h3>
<p>Creates an instance representing an error that occurs when a numeric variable or parameter is outside of its valid range.</p>
<pre><code class="lang-js"><span class="hljs-comment">// Call console with too many arguments</span>
<span class="hljs-built_in">console</span>.log.apply(<span class="hljs-built_in">console</span>, <span class="hljs-keyword">new</span> <span class="hljs-built_in">Array</span>(<span class="hljs-number">1000000000</span>)); <span class="hljs-comment">// RangeError: Invalid array length</span>
</code></pre>
<h3 id="referenceerror">ReferenceError</h3>
<p>Creates an instance representing an error that occurs when de-referencing an invalid reference. e.g.</p>
<pre><code class="lang-js"><span class="hljs-meta">'use strict'</span>;
<span class="hljs-built_in">console</span>.log(notValidVar); <span class="hljs-comment">// ReferenceError: notValidVar is not defined</span>
</code></pre>
<h3 id="syntaxerror">SyntaxError</h3>
<p>Creates an instance representing a syntax error that occurs while parsing code that isn't valid JavaScript.</p>
<pre><code class="lang-js"><span class="hljs-number">1</span>***<span class="hljs-number">3</span>; <span class="hljs-comment">// SyntaxError: Unexpected token *</span>
</code></pre>
<h3 id="typeerror">TypeError</h3>
<p>Creates an instance representing an error that occurs when a variable or parameter is not of a valid type.</p>
<pre><code class="lang-js">(<span class="hljs-string">'1.2'</span>).toPrecision(<span class="hljs-number">1</span>); <span class="hljs-comment">// TypeError: '1.2'.toPrecision is not a function</span>
</code></pre>
<h3 id="urierror">URIError</h3>
<p>Creates an instance representing an error that occurs when <code>encodeURI()</code> or <code>decodeURI()</code> are passed invalid parameters.</p>
<pre><code class="lang-js"><span class="hljs-built_in">decodeURI</span>(<span class="hljs-string">'%'</span>); <span class="hljs-comment">// URIError: URI malformed</span>
</code></pre>
<h2 id="always-use-error">Always use <code>Error</code></h2>
<p>Beginner JavaScript developers sometimes just throw raw strings e.g.</p>
<pre><code class="lang-js"><span class="hljs-keyword">try</span> {
  <span class="hljs-keyword">throw</span> <span class="hljs-string">'Something bad happened'</span>;
}
<span class="hljs-keyword">catch</span>(e) {
  <span class="hljs-built_in">console</span>.log(e);
}
</code></pre>
<p><em>Don't do that</em>. The fundamental benefit of <code>Error</code> objects is that they automatically keep track of where they were built and originated with the <code>stack</code> property.</p>
<p>Raw strings result in a very painful debugging experience and complicate error analysis from logs.</p>
<h2 id="you-dont-have-to-throw-an-error">You don't have to <code>throw</code> an error</h2>
<p>It is okay to pass an <code>Error</code> object around. This is conventional in Node.js callback style code which takes callbacks with the first argument as an error object.</p>
<pre><code class="lang-js"><span class="hljs-function"><span class="hljs-keyword">function</span> <span class="hljs-title">myFunction</span> (<span class="hljs-params">callback: (e?: Error</span>)) </span>{
  doSomethingAsync(<span class="hljs-function"><span class="hljs-keyword">function</span> (<span class="hljs-params"></span>) </span>{
    <span class="hljs-keyword">if</span> (somethingWrong) {
      callback(<span class="hljs-keyword">new</span> <span class="hljs-built_in">Error</span>(<span class="hljs-string">'This is my error'</span>))
    } <span class="hljs-keyword">else</span> {
      callback();
    }
  });
}
</code></pre>
<h2 id="exceptional-cases">Exceptional cases</h2>
<p><code>Exceptions should be exceptional</code> is a common saying in computer science. There are a few reasons why this is true for JavaScript (and TypeScript) as well.</p>
<h3 id="unclear-where-it-is-thrown">Unclear where it is thrown</h3>
<p>Consider the following piece of code:</p>
<pre><code class="lang-js"><span class="hljs-keyword">try</span> {
  <span class="hljs-keyword">const</span> foo = runTask1();
  <span class="hljs-keyword">const</span> bar = runTask2();
}
<span class="hljs-keyword">catch</span>(e) {
  <span class="hljs-built_in">console</span>.log(<span class="hljs-string">'Error:'</span>, e);
}
</code></pre>
<p>The next developer cannot know which function might throw the error. The person reviewing the code cannot know without reading the code for task1 / task2 and other functions they might call etc.</p>
<h3 id="makes-graceful-handling-hard">Makes graceful handling hard</h3>
<p>You can try to make it graceful with explicit catch around each thing that might throw:</p>
<pre><code class="lang-js"><span class="hljs-keyword">try</span> {
  <span class="hljs-keyword">const</span> foo = runTask1();
}
<span class="hljs-keyword">catch</span>(e) {
  <span class="hljs-built_in">console</span>.log(<span class="hljs-string">'Error:'</span>, e);
}
<span class="hljs-keyword">try</span> {
  <span class="hljs-keyword">const</span> bar = runTask2();
}
<span class="hljs-keyword">catch</span>(e) {
  <span class="hljs-built_in">console</span>.log(<span class="hljs-string">'Error:'</span>, e);
}
</code></pre>
<p>But now if you need to pass stuff from the first task to the second one the code becomes messy: (notice <code>foo</code> mutation requiring <code>let</code> + explicit need for annotating it because it cannot be inferred from the return of <code>runTask1</code>):</p>
<pre><code class="lang-ts"><span class="hljs-keyword">let</span> foo: <span class="hljs-built_in">number</span>; <span class="hljs-comment">// Notice use of `let` and explicit type annotation</span>
<span class="hljs-keyword">try</span> {
  foo = runTask1();
}
<span class="hljs-keyword">catch</span>(e) {
  <span class="hljs-built_in">console</span>.log(<span class="hljs-string">'Error:'</span>, e);
}
<span class="hljs-keyword">try</span> {
  <span class="hljs-keyword">const</span> bar = runTask2(foo);
}
<span class="hljs-keyword">catch</span>(e) {
  <span class="hljs-built_in">console</span>.log(<span class="hljs-string">'Error:'</span>, e);
}
</code></pre>
<h3 id="not-well-represented-in-the-type-system">Not well represented in the type system</h3>
<p>Consider the function:</p>
<pre><code class="lang-ts"><span class="hljs-function"><span class="hljs-keyword">function</span> <span class="hljs-title">validate</span>(<span class="hljs-params">value: <span class="hljs-built_in">number</span></span>) </span>{
  <span class="hljs-keyword">if</span> (value < <span class="hljs-number">0</span> || value > <span class="hljs-number">100</span>) <span class="hljs-keyword">throw</span> <span class="hljs-keyword">new</span> <span class="hljs-built_in">Error</span>(<span class="hljs-string">'Invalid value'</span>);
}
</code></pre>
<p>Using <code>Error</code> for such cases is a bad idea as it is not represented in the type definition for the validate function (which is <code>(value:number) => void</code>). Instead a better way to create a validate method would be:</p>
<pre><code class="lang-ts"><span class="hljs-function"><span class="hljs-keyword">function</span> <span class="hljs-title">validate</span>(<span class="hljs-params">value: <span class="hljs-built_in">number</span></span>): </span>{error?: <span class="hljs-built_in">string</span>} {
  <span class="hljs-keyword">if</span> (value < <span class="hljs-number">0</span> || value > <span class="hljs-number">100</span>) <span class="hljs-keyword">return</span> {error:<span class="hljs-string">'Invalid value'</span>};
}
</code></pre>
<p>And now its represented in the type system.</p>
<blockquote>
    <p>Unless you want to handle the error in a very generic (simple / catch-all etc) way, don't <em>throw</em> an error.</p>
</blockquote>